version: '3.7'

services:
  lakefs:
    image: treeverse/lakefs:latest
    ports:
      - "8000:8000"
    environment:
      - LAKEFS_DATABASE_TYPE=local
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=${LAKEFS_AUTH_ENCRYPT_SECRET_KEY}
      - LAKEFS_BLOCKSTORE_TYPE=s3
      - LAKEFS_BLOCKSTORE_S3_REGION=us-east-1
      - LAKEFS_BLOCKSTORE_S3_ENDPOINT=https://s3.amazonaws.com
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID=${LAKEFS_S3_ACCESS_KEY}
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY=${LAKEFS_S3_SECRET_KEY}
    volumes:
      - lakefs_data:/home/lakefs/.lakefs  # 🔒 persist LakeFS metadata

volumes:
  lakefs_data:
